spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/15101065186/confi-reop.git
          username: 15101065186
          password: mishigudi1
         # search-paths: /confi-reop
server:
  port: 9999